Rails.application.routes.draw do
  # Mount Brawo CMS Engine
  mount Brawo::Engine, at: "/brawo"
  
  # Brawo CMS routes are auto-generated by the gem
  # Content type routes are registered automatically when content types are loaded
  namespace :admin do
    get "dashboard/index"
    resources :content_types
    resources :settings
  end
  get "home/index"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

# Define Brawo Engine routes
Brawo::Engine.routes.draw do
  namespace :admin, path: 'admin' do
    get '/', to: 'dashboard#index', as: 'dashboard'
    
    # Content entries routes for each content type
    get ':content_type_slug', to: 'content_entries#index', as: :content_entries
    get ':content_type_slug/new', to: 'content_entries#new', as: :new_content_entry
    post ':content_type_slug', to: 'content_entries#create'
    get ':content_type_slug/:id/edit', to: 'content_entries#edit', as: :edit_content_entry
    patch ':content_type_slug/:id', to: 'content_entries#update', as: :content_entry
    put ':content_type_slug/:id', to: 'content_entries#update'
    delete ':content_type_slug/:id', to: 'content_entries#destroy'
  end
end
