# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Use the parent Gemfile and gemspec
gem "brawo_cms", path: "../.."

gem "rails", ">= 6.0.0"

gem "sqlite3", ">= 1.4"

group :development, :test do
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "bootsnap", ">= 1.4.4" # Optional, speeds up boot time
end

